### PR TITLE
Change signal handling when a debugger is attached.

### LINKED ISSUE #191: xania crashes if gdb connects after it starts then tries to set a breakpoint

### PR DESCRIPTION
**Pull request by mattgodbolt**
Continue to block SIGINT and handle it as a shutdown, but if a
debugger is detected, instead raise a SIGTRAP to hit a breakpoint.

Closes #191 (I think). I tested it with running under `gdb`, and with `gdb -p` and it did the Right Thing™ as far as I could tell, but I didn't test under vscode (sorry; I was lazy...)

Would you mind checking to see if this fixes things for you, @snellers? Thanks!

### CODE REVIEW

File: src/comm.cpp [hunk 1]
```diff
@@ -283,6 +302,7 @@ void game_loop_unix(Fd control) {
          * Poll all active descriptors.
          */
         FD_ZERO(&in_set);
+        FD_ZERO(&in_set);
```
Comment (snellers) [inline src/comm.cpp:305]: FD_ZERO on in_set twice?

File: src/comm.cpp [hunk 2]
```diff
@@ -126,6 +128,21 @@ void greet(Descriptor &d) {
     d.write(greeting->text());
 }
 
+namespace {
+bool is_being_debugged() {
+    std::ifstream t("/proc/self/status");
```
Comment (snellers) [inline src/comm.cpp:133]: aha yes, I'd read about this :)

Comment (snellers) [reply src/comm.cpp:133]: There ought to be a standard API for this sort of thing like in Windows.

**Comment by snellers** [comment]
@mattgodbolt  works perfectly, thanks!

File: src/comm.cpp (hunk 2 above)
Comment (mattgodbolt) [reply src/comm.cpp:133]: Yeah it's a pain in the proverbials...this is the best I could find.

File: src/comm.cpp (hunk 1 above)
Comment (mattgodbolt) [reply src/comm.cpp:305]: Oh...sometimes it doesn't work first time, and you have to do it again...
er....whoops no, just a typo :blush:

**Comment by mattgodbolt** [comment]
Thanks chap!
